name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.4
  - annotated-types=0.7.0
  - archspec=0.2.3
  - binutils=2.45
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - boltons=25.0.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-compiler=1.11.0
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - clang=21.1.5
  - clang-21=21.1.5
  - clangxx=21.1.5
  - cmake=4.1.2
  - colorama=0.4.6
  - compiler-rt21=21.1.5
  - compiler-rt21_linux-64=21.1.5
  - conda=25.9.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-gcc-specs=14.3.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - cxx-compiler=1.11.0
  - distro=1.9.0
  - expat=2.7.1
  - fmt=11.2.0
  - frozendict=2.4.7
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kernel-headers_linux-64=5.14.0
  - krb5=1.20.1
  - ld_impl_linux-64=2.45
  - libarchive=3.8.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.5
  - libcurl=8.16.0
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - libllvm21=21.1.5
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsanitizer=14.3.0
  - libsolv=0.7.35
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libunistring=0.9.10
  - libuuid=2.41.2
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lld=21.1.5
  - llvm-openmp=21.1.5
  - lz4-c=1.10.0
  - lzo=2.10
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.4.1
  - ncurses=6.5
  - ninja=1.13.1
  - nlohmann_json=3.11.2
  - numpy=2.3.4
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python_abi=3.11
  - pyyaml=6.0.3
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rhash=1.4.6
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - setuptools=80.9.0
  - simdjson=3.10.1
  - spdlog=1.16.0
  - sqlite=3.51.0
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - tqdm=4.67.1
  - truststore=0.10.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025a
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /opt/conda
